GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe"
}

###
DELETE http://localhost:3001/api/persons/1