### Add new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "After refactoring",
  "author": "John Doe",
  "url": "google.com",
  "likes": 2
}

### Get all blogs
GET http://localhost:3003/api/blogs

### Get all users 
GET http://localhost:3003/api/users

### Create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "gminlee",
  "name": "Min Lee",
  "password": "adminpw"
}

### Login user and get token
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "gminlee",
  "password": "adminpw"
}