### Add new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdtaW5sZWUiLCJpZCI6IjYzZjQ4MTJkYzZhNjg5MTZmMzkwYmMyMiIsImlhdCI6MTY3NzkwMTAwMSwiZXhwIjoxNjc3OTA0NjAxfQ.J13M0nfwYqDVxuxZwkWmyLy1xgTKbrl7VcBBdGrz_RQ

{
  "title": "With authentication",
  "author": "John Doe",
  "url": "google.com",
  "likes": 2
}
### Add new comment
POST http://localhost:3003/api/blogs/6402ad280a8df5c37ce4164e/comments
Content-Type: application/json

{
  "comment": "Another comment"
}

### Get all blogs
GET http://localhost:3003/api/blogs

### Get all users 
GET http://localhost:3003/api/users

### Create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "adminpw"
}

### Login user and get token
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "gminlee",
  "password": "adminpw"
}